Introduce variables for overriding ELB health check settings
ONSdigital/eq-ecs-deploy pull request #10
Opened 2018-02-21 07:43 UTC by samiwel

### Description

This PR introduces 4 new variables in order to allow `eq-ecs-deploy` module instances to override health check configuration.

Sensible defaults have been provided so that module instances are not required to specify these values.

This change is required to support a change to the eq-terraform project, where the author, author-api and publisher have been converted to be eq-ecs-deploy module instances. The author application, in particular, needs a longer time to become "healthy" since static assets are compiled at runtime, which can take a bit of time.

===

There is also an [option that can be used to set the health check grace period on 
ecs_service](https://www.terraform.io/docs/providers/aws/r/ecs_service.html#health_check_grace_period_seconds), which would be preferable to use. However this is not available unless the aws provider is updated to version >= 1.7.

I investigated this approach, but terraform complained about the conflicting provider versions used when run from eq-terraform. Introducing these variables instead is a simpler solution until the plugin can be upgraded.

### How to review

Ensure that changes look sensible.
Should be able to provision environment as before using eq-terraform.

2018-02-21 07:43 UTC, samiwel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable database backups on pre-production (5)](https://trello.com/c/tHc1N1cG/346-enable-database-backups-on-pre-production-5)

2018-02-21 09:22 UTC, jonnyshaw89 commented
I think we should try and resolve the version issue now otherwise we will never be able to use any new AWS features.
This is the line that is causing the version conflict.
https://github.com/ONSdigital/eq-terraform-dynamodb/blob/master/aws.tf#L5
I don't think that this Dynamo module need to be locked to that version

2018-02-21 14:17 UTC, jonnyshaw89 commented
@samiwel i think we should probably just close this one and open again when on top of the latest version?

2018-02-22 12:42 UTC, samiwel commented
@jonnyshaw89 I've rebased, do you think we still need a new PR, I've updated the description to reflect the changes.

2018-02-22 12:46 UTC, jonnyshaw89 commented
@samiwel ah cool. just need to update the Title now then.
also run `terraform fmt` as the 2nd file isn't formatted

2018-02-26 09:32 UTC, jonnyshaw89 requested changes

2018-02-26 09:32 UTC, jonnyshaw89 commented on ecs.tf
> +  health_check_grace_period_seconds = "${var.healthcheck_grace_period_seconds}"
@samiwel this isn't formatted correctly.
you need to run `terraform fmt`

2018-02-26 17:19 UTC, jonnyshaw89 approved these changes

2018-02-27 07:41 UTC, shahi645 approved these changes

2018-02-27 07:47 UTC, merged