Reintroduce dependency on aws_lb_listener
ONSdigital/eq-ecs-deploy pull request #15
Opened 2018-03-05 16:10 UTC by jonnyshaw89

- This will prevent the race condition that we are currently experiencing when running terraform

Currently we are seeing the error `no listener exists for load balancer`

2018-03-09 09:41 UTC, dwyeradam approved these changes

2018-03-12 12:11 UTC, MIslam92 approved these changes

2018-03-12 12:55 UTC, MIslam92 requested changes
Blocking until fixed

2018-03-12 12:56 UTC, jonnyshaw89 commented
@MIslam92 can you share the error message?

2018-03-12 13:35 UTC, jonnyshaw89 commented
@MIslam92 Mine deployed fine.

2018-03-12 13:36 UTC, MIslam92 commented
@jonnyshaw89 
Below:

Error: Error running plan: 1 error(s) occurred:

* module.survey-launcher-for-elastic-beanstalk.aws_ecs_service.service: 1 error(s) occurred:

* module.survey-launcher-for-elastic-beanstalk.aws_ecs_service.service: Resource 'aws_ecs_task_definition.task_definition' not found for variable 'aws_ecs_task_definition.task_definition.family'

2018-03-12 13:55 UTC, MIslam92 approved these changes
Somehow it works now?!
LGTM

2018-03-12 14:05 UTC, merged