Create common ecs deploy
ONSdigital/eq-ecs-deploy pull request #2
Opened 2017-10-13 15:30 UTC by jonnyshaw89

This module can be used directly to deploy any docker container to ECS

This can be tested by running the code in https://github.com/ONSdigital/eq-terraform/pull/100

2017-10-16 16:48 UTC, ajmaddaford requested changes

2017-10-16 16:48 UTC, ajmaddaford commented on ecs.tf
> +  name   = "${var.env}_iam_for_survey_register"
I think this name needs changing

2017-10-17 14:27 UTC, ajmaddaford approved these changes

2017-10-17 15:44 UTC, MIslam92 approved these changes

2017-10-17 16:11 UTC, merged