Allow a list of path patterns
ONSdigital/eq-ecs-deploy pull request #20
Opened 2018-11-20 12:50 UTC by jonnyshaw89

- Allows for multiple paths to be routed to the same container

This PR is intended to allow Author to run on a single url.
This allows for a merge of the author apps to be seamless to the user as the url will not change

2018-12-03 12:44 UTC, bitdivision requested changes
Some pedantic points...

2018-12-03 12:44 UTC, bitdivision commented on ecs.tf
> +  value = "https://${element(coalescelist(aws_route53_record.dns_record.*.name, list(var.dns_record_name)), 0)}"
Cool, didn't know about this :+1:

2018-12-03 12:44 UTC, bitdivision commented on global_vars.tf
>  variable "alb_listener_path_pattern" {
Variable name should be plural?

2018-12-03 12:44 UTC, bitdivision commented on global_vars.tf
>    description = "The path pattern to match to route to this service"
Update for multiple patterns

2018-12-04 09:41 UTC, jonnyshaw89 commented
@bitdivision comments addressed

2018-12-06 14:00 UTC, bitdivision approved these changes

2018-12-17 09:16 UTC, jonnyshaw89 commented
Not really needed yet

2018-12-17 09:16 UTC, closed without merging